from backend.config.companies.base import CompanyConfig

CONSULTING_COMPANIES = [
    CompanyConfig(
        name="Capgemini",
        slug="capgemini",
        sector="consulting",
        careers_url="https://www.capgemini.com/careers/job-search/",
        include_paths=["/careers/*", "/jobs/*", "/job/*"],
        search_query="invent data ai machine learning",
    ),
    CompanyConfig(
        name="Deloitte",
        slug="deloitte",
        sector="consulting",
        careers_url="https://apply.deloitte.com/careers/SearchJobs",
        include_paths=["/careers/*"],
        search_query="ai data strategy machine learning",
    ),
    CompanyConfig(
        name="Accenture",
        slug="accenture",
        sector="consulting",
        careers_url="https://www.accenture.com/us-en/careers/jobsearch",
        include_paths=["/us-en/careers/*"],
        search_query="ai data analytics machine learning",
    ),
    CompanyConfig(
        name="McKinsey",
        slug="mckinsey",
        sector="consulting",
        careers_url="https://www.mckinsey.com/careers/search-jobs",
        include_paths=["/careers/*"],
        search_query="data ai analytics",
    ),
    CompanyConfig(
        name="BCG",
        slug="bcg",
        sector="consulting",
        careers_url="https://careers.bcg.com/job-search",
        include_paths=["/*"],
        search_query="data ai machine learning",
    ),
    CompanyConfig(
        name="EY",
        slug="ey",
        sector="consulting",
        careers_url="https://careers.ey.com/ey/search",
        include_paths=["/*"],
        search_query="ai data strategy analytics",
    ),
    CompanyConfig(
        name="PwC",
        slug="pwc",
        sector="consulting",
        careers_url="https://www.pwc.com/us/en/careers.html",
        include_paths=["/us/en/careers/*"],
        search_query="ai data analytics machine learning",
    ),
    CompanyConfig(
        name="KPMG",
        slug="kpmg",
        sector="consulting",
        careers_url="https://www.kpmg.us/careers.html",
        include_paths=["/careers/*"],
        search_query="ai data analytics",
    ),
    CompanyConfig(
        name="Bain",
        slug="bain",
        sector="consulting",
        careers_url="https://www.bain.com/careers/",
        include_paths=["/careers/*"],
        search_query="data ai analytics",
    ),
]
