from backend.config.companies.base import CompanyConfig

TECH_COMPANIES = [
    CompanyConfig(
        name="Google",
        slug="google",
        sector="tech",
        careers_url="https://www.google.com/about/careers/applications/jobs/results/",
        include_paths=["/about/careers/*"],
        search_query="ai machine learning data",
    ),
    CompanyConfig(
        name="Microsoft",
        slug="microsoft",
        sector="tech",
        careers_url="https://careers.microsoft.com/us/en/search-results",
        include_paths=["/us/en/*"],
        search_query="ai machine learning data",
    ),
    CompanyConfig(
        name="Amazon",
        slug="amazon",
        sector="tech",
        careers_url="https://www.amazon.jobs/en/search",
        include_paths=["/en/*"],
        search_query="ai machine learning data scientist",
    ),
    CompanyConfig(
        name="Meta",
        slug="meta",
        sector="tech",
        careers_url="https://www.metacareers.com/jobs/",
        include_paths=["/jobs/*"],
        search_query="ai machine learning data",
    ),
    CompanyConfig(
        name="Apple",
        slug="apple",
        sector="tech",
        careers_url="https://jobs.apple.com/en-us/search",
        include_paths=["/en-us/*"],
        search_query="machine learning ai data",
    ),
    CompanyConfig(
        name="OpenAI",
        slug="openai",
        sector="tech",
        careers_url="https://openai.com/careers/search/",
        include_paths=["/careers/*"],
        search_query="ai research engineer",
    ),
    CompanyConfig(
        name="Anthropic",
        slug="anthropic",
        sector="tech",
        careers_url="https://www.anthropic.com/careers",
        include_paths=["/careers/*"],
        search_query="ai research engineer",
    ),
    CompanyConfig(
        name="Databricks",
        slug="databricks",
        sector="tech",
        careers_url="https://www.databricks.com/company/careers/open-positions",
        include_paths=["/company/careers/*"],
        search_query="data ai machine learning",
    ),
    CompanyConfig(
        name="Snowflake",
        slug="snowflake",
        sector="tech",
        careers_url="https://careers.snowflake.com/us/en/search-results",
        include_paths=["/us/en/*"],
        search_query="data ai machine learning",
    ),
    CompanyConfig(
        name="Palantir",
        slug="palantir",
        sector="tech",
        careers_url="https://www.palantir.com/careers/",
        include_paths=["/careers/*"],
        search_query="data ai machine learning",
    ),
]
